name: Isort
on: [push]

jobs:
  lint:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: jamescurtin/isort-action@master
        with:
          requirementsFiles: "requirements.txt requirements-test.txt"
     
